server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: rammstein-1
    url: jdbc:mysql://localhost:3306/lovedb
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: false
    url: jdbc:mysql://localhost:3306/
    schemas: lovedb
    user: root
    password: admin123
    baseline-on-migrate: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

lovesecurity:
  app:
    jwtSecret: l0v34ndD0n4t3
    jwtExpirationMs: 86400000